# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class DeDupeResult(BaseModel):
    merged_results: typing.List[str]

class DynamicGraph(BaseModel):
    nodes: typing.List["SimpleNode"]
    relationships: typing.List["SimpleRelationship"]

class Properties(BaseModel):
    description: typing.Optional[str] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class SimpleNode(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[str] = None
    properties: typing.Optional["Properties"] = None

class SimpleRelationship(BaseModel):
    source_node_id: typing.Optional[str] = None
    source_node_type: typing.Optional[str] = None
    target_node_id: typing.Optional[str] = None
    target_node_type: typing.Optional[str] = None
    type: typing.Optional[str] = None
    properties: typing.Optional["Properties"] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
