# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DeDupeResult": types.DeDupeResult,
    "stream_types.DeDupeResult": stream_types.DeDupeResult,

    "types.DynamicGraph": types.DynamicGraph,
    "stream_types.DynamicGraph": stream_types.DynamicGraph,

    "types.Properties": types.Properties,
    "stream_types.Properties": stream_types.Properties,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.SimpleNode": types.SimpleNode,
    "stream_types.SimpleNode": stream_types.SimpleNode,

    "types.SimpleRelationship": types.SimpleRelationship,
    "stream_types.SimpleRelationship": stream_types.SimpleRelationship,


}